services:
  server:
    image: node:18-alpine
    container_name: bs-bazaar-server
    working_dir: /app
    environment:
      NODE_ENV: production
    env_file:
      - ./server/.env.production
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    command: >
      sh -lc "apk add --no-cache bash python3 py3-pip >/dev/null 2>&1 || true;
      if [ -f package-lock.json ]; then npm ci --omit=dev || npm i --omit=dev; fi;
      chmod +x ./start.sh;
      ./start.sh"
    ports:
      - "3001:3001"
    networks:
      - bazaar-net
    restart: unless-stopped

  nginx:
    image: nginx:1.29-alpine
    container_name: bs-bazaar-nginx
    depends_on:
      - server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./bazaar-client/build:/usr/share/nginx/html:ro
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - bazaar-net
    restart: unless-stopped

networks:
  bazaar-net:
    driver: bridge

volumes:
  server_node_modules:
